In [2]:
import numpy as np
from sklearn.datasets import load_iris
iris = load_iris()

# Split the dataset into features (X) and target variable (y)
X = iris.data[:, 1:]  # Using only the last 3 features (excluding sepal length)
y = iris.data[:, 0]   # Sepal length




In [3]:
y.shape

(150,)

In [7]:

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import MinMaxScaler
import numpy as np

X_train=X
y_train=y


In [9]:
scaler_X = MinMaxScaler()

X_train_scaled = scaler_X.fit_transform(X_train)

In [10]:
from sklearn.linear_model import LinearRegression
model=LinearRegression()

In [15]:
from sklearn.model_selection import LeaveOneOut
from sklearn.metrics import r2_score, mean_squared_error
loo=LeaveOneOut()
predictions = []
actual_values = []

# Perform leave-one-out cross-validation
for train_index, test_index in loo.split(X_train_scaled):
    # Get training and test data for this fold
    X_train_fold, X_test_fold = X_train_scaled[train_index], X_train_scaled[test_index]
    y_train_fold, y_test_fold = y_train[train_index], y_train[test_index]
    
    # Fit the model on the training data
    model.fit(X_train_fold, y_train_fold)
    
    # Make predictions on the test data
    y_pred_fold = model.predict(X_test_fold)
    
    # Append predictions and actual values
    predictions.append(y_pred_fold)
    actual_values.append(y_test_fold)

# Calculate mean squared error (MSE)
mse = mean_squared_error(actual_values, predictions)
print("Mean Squared Error:", mse)

Mean Squared Error: 0.10176343380434628


In [16]:
predictions

[array([5.01364579]),
 array([4.68511163]),
 array([4.75028053]),
 array([4.83050978]),
 array([5.08237285]),
 array([5.37642285]),
 array([4.90065599]),
 array([5.02165538]),
 array([4.63088808]),
 array([4.88121818]),
 array([5.21152637]),
 array([5.09793254]),
 array([4.7443088]),
 array([4.53939234]),
 array([5.17376842]),
 array([5.550225]),
 array([5.08116141]),
 array([4.95677625]),
 array([5.35775636]),
 array([5.229646]),
 array([5.15811987]),
 array([5.10534044]),
 array([4.80256622]),
 array([4.92764689]),
 array([5.31763479]),
 array([4.82819502]),
 array([4.98050133]),
 array([5.08394775]),
 array([4.94545791]),
 array([4.96691685]),
 array([4.89881828]),
 array([4.89951102]),
 array([5.55187131]),
 array([5.46931165]),
 array([4.82451535]),
 array([4.67095477]),
 array([4.93251427]),
 array([5.1424439]),
 array([4.62459057]),
 array([5.01972487]),
 array([4.8862476]),
 array([4.07710878]),
 array([4.75654907]),
 array([4.93254024]),
 array([5.46416539]),
 array([4.6301436

In [18]:
import time as t
from sklearn.model_selection import LeaveOneOut
from sklearn.metrics import r2_score, mean_squared_error
import GA_UQ
import PSO_UQ 
import pandas as pd
def train_one_leave_out_report(name,model):
    loo=LeaveOneOut()
    predictions = []
    actual_values = []
    
    for train_index, test_index in loo.split(X_train_scaled):
        # Get training and test data for this fold
        X_train_fold, X_test_fold = X_train_scaled[train_index], X_train_scaled[test_index]
        y_train_fold, y_test_fold = y_train[train_index], y_train[test_index]
        
        # Fit the model on the training data
        model.fit(X_train_fold, y_train_fold)
        
        # Make predictions on the test data
        y_pred_fold = model.predict(X_test_fold)
        
        # Append predictions and actual values
        predictions.append(y_pred_fold[0])
        actual_values.append(y_test_fold[0])
    # Calculate R2 and RMSE for test set
    test_r2 = r2_score(actual_values, predictions)
    test_rmse = mean_squared_error(actual_values, predictions, squared=False)
    
    start_time=t.time()
    solution,solution_fitness, ga_instance=GA_UQ.GA_UQ(predictions,actual_values)
    ga_duration=t.time()-start_time
    
    start_time=t.time()
    pos,cost,optimizer=PSO_UQ.PSO_UQ(predictions,actual_values)
    pso_duration=t.time()-start_time
    
        
    # Store results in a dictionary
    result = {
            "Model": name,
            #"Train R2": train_r2,
            #"Train RMSE": train_rmse,
            "R2": test_r2,
            "RMSE": test_rmse,
            "a_PSO":pos[0],
            "b_PSO":pos[1],
            "Fitness_PSO":cost*-1,
            "time_PSO":pso_duration,
            "a_GA":solution[0],
            "b_GA":solution[1],
            "Fitness_GA":solution_fitness,
            "time_GA":ga_duration
    }
    results.append(result)
    print(result)
    

In [18]:
results = []

In [19]:
from sklearn.linear_model import LinearRegression
trainAndreport("Linear Regression",LinearRegression())

c:\Users\naima\AppData\Local\Programs\Python\Python311\Lib\site-packages\pygad\pygad.py:748: UserWarning: The percentage of genes to mutate (mutation_percent_genes=10) resutled in selecting (0) genes. The number of genes to mutate is set to 1 (mutation_num_genes=1).
If you do not want to mutate any gene, please set mutation_type=None.
  warnings.warn(f"The percentage of genes to mutate (mutation_percent_genes={mutation_percent_genes}) resutled in selecting ({mutation_num_genes}) genes. The number of genes to mutate is set to 1 (mutation_num_genes=1).\nIf you do not want to mutate any gene, please set mutation_type=None.")
2024-03-13 10:45:51,186 - pyswarms.single.global_best - INFO - Optimize for 1000 iters with {'c1': 0.5, 'c2': 0.3, 'w': 0.9}
pyswarms.single.global_best: 100%|██████████|1000/1000, best_cost=-.372
2024-03-13 10:45:52,434 - pyswarms.single.global_best - INFO - Optimization finished | best cost: -0.3724996789083619, best pos: [0.37910324 0.81518107]


{'Model': 'Linear Regression', 'R2': 0.8520477902310161, 'RMSE': 0.3195723371369994, 'a_PSO': 0.37910323563215, 'b_PSO': 0.8151810717343011, 'Fitness_PSO': 0.3724996789083619, 'time_PSO': 1.2498133182525635, 'a_GA': 0.3920626148994266, 'b_GA': 0.817290083519866, 'Fitness_GA': 0.3727027013955109, 'time_GA': 0.09936070442199707}


In [20]:
from sklearn.svm import SVR
trainAndreport("SVR",SVR())


c:\Users\naima\AppData\Local\Programs\Python\Python311\Lib\site-packages\pygad\pygad.py:748: UserWarning: The percentage of genes to mutate (mutation_percent_genes=10) resutled in selecting (0) genes. The number of genes to mutate is set to 1 (mutation_num_genes=1).
If you do not want to mutate any gene, please set mutation_type=None.
  warnings.warn(f"The percentage of genes to mutate (mutation_percent_genes={mutation_percent_genes}) resutled in selecting ({mutation_num_genes}) genes. The number of genes to mutate is set to 1 (mutation_num_genes=1).\nIf you do not want to mutate any gene, please set mutation_type=None.")
2024-03-13 10:45:54,571 - pyswarms.single.global_best - INFO - Optimize for 1000 iters with {'c1': 0.5, 'c2': 0.3, 'w': 0.9}
pyswarms.single.global_best: 100%|██████████|1000/1000, best_cost=-.358
2024-03-13 10:45:55,792 - pyswarms.single.global_best - INFO - Optimization finished | best cost: -0.35801272375847804, best pos: [0.50501207 0.87633806]


{'Model': 'SVR', 'R2': 0.8337358353177521, 'RMSE': 0.33877221069818136, 'a_PSO': 0.5050120735002277, 'b_PSO': 0.8763380594830856, 'Fitness_PSO': 0.35801272375847804, 'time_PSO': 1.2235493659973145, 'a_GA': 0.47364138364893504, 'b_GA': 0.9075573055082464, 'Fitness_GA': 0.35819101589284263, 'time_GA': 0.10099554061889648}


In [21]:
from sklearn.ensemble import RandomForestRegressor
trainAndreport("Random Forest", RandomForestRegressor())

c:\Users\naima\AppData\Local\Programs\Python\Python311\Lib\site-packages\pygad\pygad.py:748: UserWarning: The percentage of genes to mutate (mutation_percent_genes=10) resutled in selecting (0) genes. The number of genes to mutate is set to 1 (mutation_num_genes=1).
If you do not want to mutate any gene, please set mutation_type=None.
  warnings.warn(f"The percentage of genes to mutate (mutation_percent_genes={mutation_percent_genes}) resutled in selecting ({mutation_num_genes}) genes. The number of genes to mutate is set to 1 (mutation_num_genes=1).\nIf you do not want to mutate any gene, please set mutation_type=None.")
2024-03-13 10:45:57,341 - pyswarms.single.global_best - INFO - Optimize for 1000 iters with {'c1': 0.5, 'c2': 0.3, 'w': 0.9}
pyswarms.single.global_best: 100%|██████████|1000/1000, best_cost=-.367
2024-03-13 10:45:58,514 - pyswarms.single.global_best - INFO - Optimization finished | best cost: -0.3669552186752642, best pos: [0.37696893 0.88127233]


{'Model': 'Random Forest', 'R2': 0.8606566793048744, 'RMSE': 0.31013553407903566, 'a_PSO': 0.37696893307014534, 'b_PSO': 0.8812723252760064, 'Fitness_PSO': 0.3669552186752642, 'time_PSO': 1.1782841682434082, 'a_GA': 0.39590657322253087, 'b_GA': 0.8857847917661288, 'Fitness_GA': 0.3668851521266927, 'time_GA': 0.1046593189239502}


In [22]:
from sklearn.ensemble import GradientBoostingRegressor
trainAndreport("GradientBoostingRegressor", GradientBoostingRegressor())

c:\Users\naima\AppData\Local\Programs\Python\Python311\Lib\site-packages\pygad\pygad.py:748: UserWarning: The percentage of genes to mutate (mutation_percent_genes=10) resutled in selecting (0) genes. The number of genes to mutate is set to 1 (mutation_num_genes=1).
If you do not want to mutate any gene, please set mutation_type=None.
  warnings.warn(f"The percentage of genes to mutate (mutation_percent_genes={mutation_percent_genes}) resutled in selecting ({mutation_num_genes}) genes. The number of genes to mutate is set to 1 (mutation_num_genes=1).\nIf you do not want to mutate any gene, please set mutation_type=None.")
2024-03-13 10:46:01,202 - pyswarms.single.global_best - INFO - Optimize for 1000 iters with {'c1': 0.5, 'c2': 0.3, 'w': 0.9}
pyswarms.single.global_best: 100%|██████████|1000/1000, best_cost=-.346
2024-03-13 10:46:02,416 - pyswarms.single.global_best - INFO - Optimization finished | best cost: -0.3456461987589039, best pos: [0.43162978 1.24516431]


{'Model': 'GradientBoostingRegressor', 'R2': 0.8346610412065091, 'RMSE': 0.3378283172804203, 'a_PSO': 0.4316297832142517, 'b_PSO': 1.2451643122724014, 'Fitness_PSO': 0.3456461987589039, 'time_PSO': 1.2353575229644775, 'a_GA': 0.40873922702945986, 'b_GA': 0.8123669319304438, 'Fitness_GA': 0.35966198789289566, 'time_GA': 0.11999917030334473}


In [23]:
# Create a DataFrame to display results
results_df = pd.DataFrame(results)
results_df=results_df.round(3)
print(results_df)

                       Model     R2   RMSE  a_PSO  b_PSO  Fitness_PSO  \
0          Linear Regression  0.852  0.320  0.379  0.815        0.372   
1                        SVR  0.834  0.339  0.505  0.876        0.358   
2              Random Forest  0.861  0.310  0.377  0.881        0.367   
3  GradientBoostingRegressor  0.835  0.338  0.432  1.245        0.346   

   time_PSO   a_GA   b_GA  Fitness_GA  time_GA  
0     1.250  0.392  0.817       0.373    0.099  
1     1.224  0.474  0.908       0.358    0.101  
2     1.178  0.396  0.886       0.367    0.105  
3     1.235  0.409  0.812       0.360    0.120  


In [26]:
print(results_df.to_latex(index=False,float_format="{:.3f}".format))

\begin{tabular}{lrrrrrrrrrr}
\toprule
Model & R2 & RMSE & a_PSO & b_PSO & Fitness_PSO & time_PSO & a_GA & b_GA & Fitness_GA & time_GA \\
\midrule
Linear Regression & 0.852 & 0.320 & 0.379 & 0.815 & 0.372 & 1.250 & 0.392 & 0.817 & 0.373 & 0.099 \\
SVR & 0.834 & 0.339 & 0.505 & 0.876 & 0.358 & 1.224 & 0.474 & 0.908 & 0.358 & 0.101 \\
Random Forest & 0.861 & 0.310 & 0.377 & 0.881 & 0.367 & 1.178 & 0.396 & 0.886 & 0.367 & 0.105 \\
GradientBoostingRegressor & 0.835 & 0.338 & 0.432 & 1.245 & 0.346 & 1.235 & 0.409 & 0.812 & 0.360 & 0.120 \\
\bottomrule
\end{tabular}

